apiVersion: v1
kind: Service
metadata:
 name: backend_spring_boot
spec:
 type: NodePort
 selector:
   app: backend_spring_boot
   env: prod
 ports:
 - name: test
   protocol: TCP
   port: 8085
   targetPort: 8085
   nodePort: 32221
