apiVersion: apps/v1
kind: Deployment
metadata:
 name: backend-test
spec:
 replicas: 2
 strategy:
  type: RollingUpdate
 selector:
  matchLabels:
   app: backend-test
 template:
   metadata:
    labels:
     app: backend-test
     env: prod
   spec:
    containers:
    - name: backend-test
      image: chaimakh/backend-test:latest
      ports:
      - containerPort: 8085
      env:
      - name: DB_URL
        value: "jdbc:postgresql://postgres:5432/kanban"
      - name: POSTGRES_USER
        value: "kanban"
      - name: POSTGRES_PASSWORD
        value: "kanban"
      - name: POSTGRES_DB
        value: "kanban"


