apiVersion: v1
kind: Service
metadata:
 name: backend-test
spec:
 type: NodePort
 selector:
   app: backend-test
   env: prod
 ports:
 - name: test
   protocol: TCP
   port: 8085
   targetPort: 8085
   nodePort: 32221
